import 'package:flutter/material.dart';
import '../../../widgets/custom_app_bar.dart';
import '../../../widgets/bottom_nav_bar.dart';
import '../../../widgets/responsive_layout.dart';

import '../../Settings/settings_1.dart';
import '../../challenges.dart';
import '../../home_page.dart';
import 'create_workout_own.dart';
import 'generate_AI_workout.dart';

class CreateWorkoutPage extends StatelessWidget {
  final int userId;

  const CreateWorkoutPage({
  super.key,
  required this.userId,
  });

  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    final horizontalPadding = screenWidth * 0.08;
    final isSmallScreen = screenWidth < 400;

    return Scaffold(
      backgroundColor: Colors.white,

      // ✅ Global custom app bar
      appBar: const CustomAppBar(title: "Create Workout"),

      // ✅ Global responsive wrapper
      body: ResponsiveLayout(
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: horizontalPadding),
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const SizedBox(height: 16),

                // Local back button (kept from original logic)
                IconButton(
                  icon: const Icon(Icons.arrow_back),
                  onPressed: () => Navigator.pop(context),
                ),
                const SizedBox(height: 16),

                // Build your own workout section
                Text(
                  'Build Your Own Workout Routine',
                  style: TextStyle(
                    fontSize: isSmallScreen ? 15 : 16,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'Create a workout routine tailored to your preferences! Choose from our library of built-in exercises or include your own custom exercises to build a routine that fits your goals, schedule, and favorite activities.',
                  style: TextStyle(fontSize: isSmallScreen ? 13 : 14),
                ),
                const SizedBox(height: 4),
                GestureDetector(
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => BuildRoutinePage(userId: userId),
                      ),
                    );
                  },
                  child: const Text(
                    '+ Build Routine',
                    style: TextStyle(
                      fontSize: 14,
                      color: Color(0xFF6B578C),
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),

                const SizedBox(height: 24),

                // AI routine section
                Text(
                  'Generate Custom Routine (AI-Powered)',
                  style: TextStyle(
                    fontSize: isSmallScreen ? 15 : 16,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'Let our AI design a personalized routine for you! Answer a few quick questions and get a custom routine generated by our AI based on your fitness level, goals, and exercise history—ready to use right away.',
                  style: TextStyle(fontSize: isSmallScreen ? 13 : 14),
                ),
                const SizedBox(height: 4),
                GestureDetector(
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) =>
                            GenerateAIRoutinePopup(userId: userId),
                      ),
                    );
                  },
                  child: const Text(
                    '+ Generate Routine',
                    style: TextStyle(
                      fontSize: 14,
                      color: Color(0xFF6B578C),
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),

      // ✅ Global bottom navigation bar
      bottomNavigationBar: const BottomNavBar(currentIndex: 2),
    );
  }
}
